apiVersion: skaffold/v1beta16
kind: Config
build:
  artifacts:
  - image: echo-server
    context: .
    docker:
      dockerfile: Dockerfile
  local:
    push: true
deploy:
  kubectl:
    manifests:
    - k8s/*.yaml
