apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
  - image: quay.io/sololabs/echo-server
    docker:
      dockerfile: Dockerfile
  local: {}
deploy:
  kubectl:
    manifests:
    - echo-server.yaml
