apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
  - image: quay.io/sololabs/echo-server
    context: .
    docker:
      dockerfile: Dockerfile
  tagPolicy:
    gitCommit: {}
  local: {}
deploy:
  kubectl:
    manifests:
    - k8s/*.yaml
